Repository RoleModel/optics, pull requests merged in 2022-09, with the labels that each got.

#73 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#83 [GHI #70] Sidebar Rail
  .storybook/documentation.scss
  .storybook/preview.js
  src/components/button.scss
  src/components/index.scss
  src/components/navigation_rail.scss
  src/core/tokens/base_tokens.scss
  src/stories/LetterSpacing.stories.js
  src/stories/LetterSpacing/LetterSpacing.js
  src/stories/LetterSpacing/LetterSpacing.mdx
  src/stories/NavigationRail.stories.js
  src/stories/NavigationRail/NavigationRail.js
  src/stories/NavigationRail/NavigationRail.mdx
  src/stories/Transition.stories.js
  src/stories/Transition/Transition.js
  src/stories/Transition/Transition.mdx
Labels: documentation, enhancement

#86 [GHI #85] Tom Select Single
  src/addons/tom-select.scss
  src/components/form.scss
  src/core/tokens/base_tokens.scss
Labels: bug

#87 [GHI #72] button icon with breakpoints
  src/components/button.scss
  src/stories/Button/Button.mdx
Labels: bug

#88 [GHI #74] Alert Scales Dark Mode
  src/core/tokens/alert_color_tokens.scss
  src/core/tokens/dark_mode_tokens.scss
  src/core/tokens/scale_color_tokens.scss
Labels: bug

#90 [GHI #40] Form Group and error messages
  src/components/form.scss
  src/stories/Form/Form.js
  src/stories/Form/Form.mdx
  src/stories/FormGroup.stories.js
Labels: bug, enhancement, Cleanup

#91 [GHI #82] Table Enhancements
  src/components/table.scss
  src/stories/Table.stories.js
  src/stories/Table/Table.js
  src/stories/Table/Table.mdx
Labels: enhancement

#93 [GHI #89] Api experiment again
  .storybook/documentation.scss
  src/components/badge.scss
  src/components/button.scss
  src/components/card.scss
  src/components/flash.scss
  src/components/table.scss
  src/core/base.scss
  src/stories/Badge/Badge.mdx
  src/stories/Button/Button.mdx
  src/stories/Card/Card.mdx
  src/stories/Flash/Flash.mdx
  src/stories/Table/Table.mdx
Labels: documentation, Cleanup, Breaking Change

#95 [GHI #94] Fix the button squish
  src/components/button.scss
Labels: bug
